---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: test
  image: ubuntu:20.04
  environment:
    PASSWORD:
      from_secret: GH_TOKEN
  commands:
  - echo "hello world"
