---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: test
  image: ubuntu:20.04
  environment:
    DEBIAN_FRONTEND: noninteractive
    cu:
      from_secret: configurl
    yt:
      from_secret: configdy
    id:
      from_id: id
  commands:
  - bash run.sh
